# Frontend (Pages) configuration only
# Deploy backend separately as a Worker

name = "pssm"
account_id = "3335093fd32547addce581d41f67ffb0"
compatibility_date = "2026-01-13"

[assets]
directory = "./dist"